# Generated by Django 4.0.1 on 2022-01-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EczeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EczeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='EczeImages')),
                ('profile', models.ManyToManyField(blank=True, null=True, to='eczema_profile.EczeProfile')),
            ],
        ),
    ]
