# Generated by Django 4.0.1 on 2022-02-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eczema_profile', '0006_activity_allergies_contactallergens_food_healthevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='activity',
        ),
        migrations.AddField(
            model_name='trigger',
            name='activity',
            field=models.ManyToManyField(to='eczema_profile.Activity'),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='allergy',
        ),
        migrations.AddField(
            model_name='trigger',
            name='allergy',
            field=models.ManyToManyField(to='eczema_profile.Allergies'),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='contact',
        ),
        migrations.AddField(
            model_name='trigger',
            name='contact',
            field=models.ManyToManyField(to='eczema_profile.ContactAllergens'),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='food',
        ),
        migrations.AddField(
            model_name='trigger',
            name='food',
            field=models.ManyToManyField(to='eczema_profile.Food'),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='health_event',
        ),
        migrations.AddField(
            model_name='trigger',
            name='health_event',
            field=models.ManyToManyField(to='eczema_profile.HealthEvent'),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='product',
        ),
        migrations.AddField(
            model_name='trigger',
            name='product',
            field=models.ManyToManyField(to='eczema_profile.Product'),
        ),
    ]
