# Generated by Django 4.0.1 on 2022-02-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eczema_profile', '0008_auto_20220203_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='eczeimage',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
